CREATE TABLE `payments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`amount` int NOT NULL,
	`currency` varchar(3) NOT NULL DEFAULT 'SAR',
	`status` enum('pending','paid','failed','refunded','cancelled') NOT NULL DEFAULT 'pending',
	`paymentMethod` enum('creditcard','mada','applepay','stcpay'),
	`gateway` enum('moyasar','tap') NOT NULL,
	`gatewayPaymentId` varchar(255),
	`gatewayResponse` text,
	`description` text,
	`itemType` enum('consultation','course','subscription','document'),
	`itemId` int,
	`discountCodeId` int,
	`discountAmount` int DEFAULT 0,
	`finalAmount` int NOT NULL,
	`refundedAmount` int DEFAULT 0,
	`refundedAt` timestamp,
	`paidAt` timestamp,
	`failedAt` timestamp,
	`errorMessage` text,
	`metadata` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `payments_id` PRIMARY KEY(`id`)
);
