CREATE TABLE `consultantAvailability` (
	`id` int AUTO_INCREMENT NOT NULL,
	`consultantId` int NOT NULL,
	`dayOfWeek` enum('sunday','monday','tuesday','wednesday','thursday','friday','saturday') NOT NULL,
	`startTime` varchar(10) NOT NULL,
	`endTime` varchar(10) NOT NULL,
	`isAvailable` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `consultantAvailability_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `consultantBlockedDates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`consultantId` int NOT NULL,
	`blockedDate` date NOT NULL,
	`reason` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `consultantBlockedDates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `consultantDocuments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`consultantId` int NOT NULL,
	`documentType` enum('cv','certificate','id','license','other') NOT NULL,
	`documentName` varchar(255) NOT NULL,
	`documentUrl` text NOT NULL,
	`fileSize` int,
	`mimeType` varchar(100),
	`verificationStatus` enum('pending','verified','rejected') NOT NULL DEFAULT 'pending',
	`verificationNotes` text,
	`verifiedBy` int,
	`verifiedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `consultantDocuments_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `consultantEarnings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`consultantId` int NOT NULL,
	`bookingId` int NOT NULL,
	`totalAmount` int NOT NULL,
	`platformCommission` int NOT NULL,
	`consultantEarning` int NOT NULL,
	`commissionRate` int NOT NULL,
	`payoutStatus` enum('pending','processing','paid','cancelled') NOT NULL DEFAULT 'pending',
	`payoutMethod` varchar(50),
	`payoutTransactionId` varchar(255),
	`payoutDate` timestamp,
	`payoutNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `consultantEarnings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `consultantReviews` (
	`id` int AUTO_INCREMENT NOT NULL,
	`consultantId` int NOT NULL,
	`bookingId` int NOT NULL,
	`clientId` int NOT NULL,
	`rating` int NOT NULL,
	`review` text,
	`professionalismRating` int,
	`communicationRating` int,
	`knowledgeRating` int,
	`timelinessRating` int,
	`isPublished` boolean NOT NULL DEFAULT true,
	`consultantResponse` text,
	`respondedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `consultantReviews_id` PRIMARY KEY(`id`),
	CONSTRAINT `consultantReviews_bookingId_unique` UNIQUE(`bookingId`)
);
--> statement-breakpoint
CREATE TABLE `consultants` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`fullNameAr` varchar(255) NOT NULL,
	`fullNameEn` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(20) NOT NULL,
	`city` varchar(100),
	`profilePicture` text,
	`mainSpecialization` varchar(100) NOT NULL,
	`subSpecializations` text,
	`yearsOfExperience` int NOT NULL,
	`qualifications` text,
	`certifications` text,
	`bioAr` text,
	`bioEn` text,
	`ibanNumber` varchar(34),
	`bankName` varchar(100),
	`accountHolderName` varchar(255),
	`commissionRate` int NOT NULL DEFAULT 20,
	`status` enum('pending','approved','rejected','suspended') NOT NULL DEFAULT 'pending',
	`rejectionReason` text,
	`approvedAt` timestamp,
	`approvedBy` int,
	`totalConsultations` int NOT NULL DEFAULT 0,
	`completedConsultations` int NOT NULL DEFAULT 0,
	`averageRating` int DEFAULT 0,
	`totalEarnings` int NOT NULL DEFAULT 0,
	`isAvailable` boolean NOT NULL DEFAULT true,
	`maxDailyBookings` int NOT NULL DEFAULT 5,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `consultants_id` PRIMARY KEY(`id`),
	CONSTRAINT `consultants_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `consultationBookings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`bookingNumber` varchar(50) NOT NULL,
	`clientId` int NOT NULL,
	`consultantId` int NOT NULL,
	`consultationTypeId` int NOT NULL,
	`scheduledDate` date NOT NULL,
	`scheduledTime` varchar(10) NOT NULL,
	`duration` int NOT NULL DEFAULT 60,
	`clientNotes` text,
	`consultantNotes` text,
	`status` enum('pending','confirmed','in-progress','completed','cancelled','no-show') NOT NULL DEFAULT 'pending',
	`cancellationReason` text,
	`cancelledBy` int,
	`cancelledAt` timestamp,
	`totalAmount` int NOT NULL,
	`discountAmount` int NOT NULL DEFAULT 0,
	`finalAmount` int NOT NULL,
	`discountCodeId` int,
	`paymentStatus` enum('pending','paid','refunded') NOT NULL DEFAULT 'pending',
	`paymentMethod` varchar(50),
	`paymentTransactionId` varchar(255),
	`paidAt` timestamp,
	`rating` int,
	`review` text,
	`reviewedAt` timestamp,
	`confirmedAt` timestamp,
	`startedAt` timestamp,
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `consultationBookings_id` PRIMARY KEY(`id`),
	CONSTRAINT `consultationBookings_bookingNumber_unique` UNIQUE(`bookingNumber`)
);
--> statement-breakpoint
CREATE TABLE `consultationTypes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`code` varchar(50) NOT NULL,
	`nameAr` varchar(255) NOT NULL,
	`nameEn` varchar(255) NOT NULL,
	`descriptionAr` text,
	`descriptionEn` text,
	`basePriceSAR` int NOT NULL,
	`estimatedDuration` int NOT NULL DEFAULT 60,
	`relatedSpecializations` text,
	`icon` varchar(100),
	`imageUrl` text,
	`color` varchar(20),
	`features` text,
	`isActive` boolean NOT NULL DEFAULT true,
	`orderIndex` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `consultationTypes_id` PRIMARY KEY(`id`),
	CONSTRAINT `consultationTypes_code_unique` UNIQUE(`code`)
);
--> statement-breakpoint
CREATE TABLE `specializations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`code` varchar(50) NOT NULL,
	`nameAr` varchar(255) NOT NULL,
	`nameEn` varchar(255) NOT NULL,
	`descriptionAr` text,
	`descriptionEn` text,
	`icon` varchar(100),
	`imageUrl` text,
	`color` varchar(20),
	`isActive` boolean NOT NULL DEFAULT true,
	`orderIndex` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `specializations_id` PRIMARY KEY(`id`),
	CONSTRAINT `specializations_code_unique` UNIQUE(`code`)
);
